name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
