name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "master"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "19.x"
      - name: Install 🔧
        run: |
          npm install
      - name: deploy
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          build_dir: storybook-static
          build_command: npm run build-storybook
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
